# Generated by Django 4.1 on 2022-08-15 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('ISBN', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ISBN libro')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo Libro')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor Libro')),
                ('numPaginas', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('numDocumento', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='numero identificacion')),
                ('tipoDocumento', models.CharField(choices=[('CC', 'Cedula'), ('TI', 'Tarjeta identidad'), ('TE', 'Cedula extranjera'), ('NIT', 'Numero tributario'), ('PAS', 'Pasaporte')], default='CC', max_length=3)),
                ('primerNombre', models.CharField(max_length=50, verbose_name='Primer nombre')),
                ('segundoNombre', models.CharField(max_length=50, verbose_name='Segundo nombre')),
                ('primerApellido', models.CharField(max_length=50, verbose_name='Primer apellido')),
                ('segundoApellido', models.CharField(max_length=50, verbose_name='Segundo apellido')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion residencia')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefono contacto')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'usuario',
                'ordering': ['primerApellido', '-segundoApellido'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('IDprestamo', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador prestamo')),
                ('fechaPrestamo', models.DateField()),
                ('fechaDevolucion', models.DateField()),
                ('ISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.libro')),
                ('numDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.usuario')),
            ],
        ),
    ]
