# Generated by Django 4.1 on 2022-08-15 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterModelTable(
            name='usuario',
            table=None,
        ),
    ]
